services:
  ny-server-api:
    image: nicholasjackson/fake-service:v0.7.1
    environment:
      - LISTEN_ADDR=0.0.0.0:9090
      - NAME=ny-server-api
      - MESSAGE=API response
      - UPSTREAM_URIS=http://192.168.30.10:9090
      - UPSTREAM_WORKERS=1
      - TRACING_ZIPKIN=http://192.168.110.10:9411
      - HTTP_CLIENT_KEEP_ALIVES=false
      - SERVER_TYPE=grpc
    ports:
      - "192.168.10.10:9090:9090"
